[workspace]
members = [
    "sharke-chip8"
]

[profile.bench]
overflow-checks = false

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false

[profile.release]
overflow-checks = false
